// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1udBcmQQCYRN6SymXuGXdPzklFrftE0',
    appId: '1:332331938609:web:10025d015eed0c8b9ff610',
    messagingSenderId: '332331938609',
    projectId: 'crudshop-5f11d',
    authDomain: 'crudshop-5f11d.firebaseapp.com',
    storageBucket: 'crudshop-5f11d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsy2s62vIiS-7hTz1oZEvV1AfvXabr08o',
    appId: '1:332331938609:android:a07b34dd47b37b1c9ff610',
    messagingSenderId: '332331938609',
    projectId: 'crudshop-5f11d',
    storageBucket: 'crudshop-5f11d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPstedB3xOmXy9YHseTTiR31TpQN20kMc',
    appId: '1:332331938609:ios:0986931216606ce59ff610',
    messagingSenderId: '332331938609',
    projectId: 'crudshop-5f11d',
    storageBucket: 'crudshop-5f11d.firebasestorage.app',
    iosBundleId: 'com.example.crudShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPstedB3xOmXy9YHseTTiR31TpQN20kMc',
    appId: '1:332331938609:ios:0986931216606ce59ff610',
    messagingSenderId: '332331938609',
    projectId: 'crudshop-5f11d',
    storageBucket: 'crudshop-5f11d.firebasestorage.app',
    iosBundleId: 'com.example.crudShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd1udBcmQQCYRN6SymXuGXdPzklFrftE0',
    appId: '1:332331938609:web:0684db6ac8b889f99ff610',
    messagingSenderId: '332331938609',
    projectId: 'crudshop-5f11d',
    authDomain: 'crudshop-5f11d.firebaseapp.com',
    storageBucket: 'crudshop-5f11d.firebasestorage.app',
  );
}